# Generated by Django 4.1.6 on 2023-04-27 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='list',
            name='type',
            field=models.CharField(choices=[('work', 'WORK'), ('school', 'SCHOOL'), ('videos', 'VIDEOS')], default='work', max_length=6),
        ),
    ]
